name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install uv and cache dependencies
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
    - name: Install dependencies
      run: uv sync --dev
    - name: Run ruff
      uses: astral-sh/ruff-action@v3
      with:
        args: "check --force-exclude"
    - name: Test with pytest
      run: uv run pytest 